### PR TITLE
Remove name <key> from tmLanguage (fixes #8)

### LINKED ISSUE #8: Stylus: cannot create newline by pressing Enter
I thought this is something on my end, until my colleague told me he is having same problem. [Here is very similar issue](https://github.com/davidrios/jade-tmbundle/issues/54) I just found.

### PR DESCRIPTION
**Pull request by azamat-sharapov**

### CODE REVIEW

**Comment by yyx990803** [comment]
Hmm, why does this fix #8? Just curious...

**Comment by yyx990803** [comment]
Ok, I think this is because giving it that name causes the stylus package to double apply auto completion or something. Just changing the name to a different name fixes it too (and make auto completion work properly!)

Can you confirm and edit the YAML as well? Just change the name to something like `source.vue-stylus.embedded.html`.

**Comment by azamat-sharapov** [comment]
> Hmm, why does this fix #8? Just curious...

@yyx990803 I didn't also understand, I borrowed idea from [here](https://github.com/davidrios/jade-tmbundle/commit/264c045cf1f51c9ded419e4ff9793d8d178157e2) :smile: 

But I think you are right, it may be conflict.  
Updated.

**Comment by yyx990803** [comment]
:+1:

**Pull request merged**
