### PR TITLE
`lang="jade"` to `lang="pug"`, Solved #72

### PR DESCRIPTION
**Pull request by YamiOdymel**
`lang="jade"` to `lang="pug"`, Solved #72

### CODE REVIEW

**Comment by yyx990803** [comment]
Pug is already supported: https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L98-L112

**Comment by GongBingQuan** [comment]
image

**Comment by GongBingQuan** [comment]
一点风格都没有了

**Comment by grafa** [comment]
Hi guys,

I'm kinda confused. When have <template lang="jade"> I get nice hilight. When I switch to "pug" all my text is almost unhilighted (pug/jade hilight is obsiously not applied).

Do I need to install or set some things up?
I use VCS 1.8.

Thank you a lot!

**Comment by YamiOdymel** [comment]
@grafa I think the issue is about the extension, 

so you have to modify the config of the extension in the VSC extension folder.

Go to `~/.vscode/extensions/hollowtree.vue-snippets/syntaxes` 

and find the `vue.tmLanguage`, open it, and replace

```html
<string>(?:^\s+)?(&lt;)((?i:template))\b(?=[^&gt;]*lang="jade(?:\?[^"]*)?")</string>
```

to

```html
<string>(?:^\s+)?(&lt;)((?i:template))\b(?=[^&gt;]*lang="pug(?:\?[^"]*)?")</string>
```

might solve your problem.

**Comment by grafa** [comment]
Hi, thanks for reply.

In the config file there are both variants. Please can you take a brief look on the file?

Thanks a lot.
[vue.tmLanguage.txt](https://github.com/vuejs/vue-syntax-highlight/files/665776/vue.tmLanguage.txt)

**Comment by YamiOdymel** [comment]
@grafa Just change L:268

```
<string>(?:^\s+)?(&lt;)((?i:template))\b(?=[^&gt;]*lang="jade(?:\?[^"]*)?")</string>
```

to

```
<string>(?:^\s+)?(&lt;)((?i:template))\b(?=[^&gt;]*lang="pug(?:\?[^"]*)?")</string>
```

and don't modify other `jade`-things.

**Comment by grafa** [comment]
Amazing, works!

Note:
But when I have in my .vue file `lang="jade"` the syntax highlight is almost off. So this is temporary solution I guess.

**Pull request closed without merging**
