### PR TITLE
Fix LESS highlighting. Fixes #137. Might impact #138

### LINKED ISSUE #137: Recently updated?In the <style lang=''> grammar block no highlight
wx20180507-192136 2x
lang
No Lang property is normal

### PR DESCRIPTION
**Pull request by skyronic**

### CODE REVIEW

**Comment by skyronic** [comment]
(This is work in progress now, will roll in more fixes for new sublime 3170 release)

**Comment by braver** [comment]
See also my PR’s #135 and #136

**Comment by skyronic** [comment]
Hi @braver. I'll close mine and merge yours instead. Thank you for your contribution!

**Comment by braver** [comment]
🎉

**Pull request closed without merging**
